name: Publish  üêç  –°odeFermenter distribution üì¶ to test PyPI

on:
  push:
    branches: [ dev ]
    tags:
      - 'v*'

jobs:
  build-n-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install Poetry
      run: pip install poetry

    - name: Install dependencies
      run: poetry install

    - name: Run mypy
      uses: jpetrucciani/mypy-check@1.0.0
      with:
        path: "codefermenter"
        mypy_flags: "--strict"

    - name: Run tests
      run: python -m unittest discover -s tests

    - name: Build and publish
      # if: startsWith(github.ref, 'refs/tags/v')
      run: |
        poetry config repositories.testpypi https://test.pypi.org/legacy/
        poetry config pypi-token.testpypi ${{ secrets.TEST_PYPI_API_TOKEN }}
        poetry publish --build -r testpypi --dry-run -vvv
